// src/components/KanbanBoard.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { Task, TaskStatus } from '../types/task'
import { priorityBorder, priorityLabel, priorityBadge } from '../constants/task'

const props = defineProps<{
  tasks: Task[]
}>()

const emit = defineEmits<{
  'update-status': [id: string, status: TaskStatus]
  toggle: [id: string]
  delete: [id: string]
}>()

// 三列定义
const columns: { status: TaskStatus; label: string; color: string; bgColor: string }[] = [
  { status: 'todo', label: '待办', color: 'text-slate-600 dark:text-slate-400', bgColor: 'bg-slate-50 dark:bg-slate-700' },
  { status: 'in-progress', label: '进行中', color: 'text-amber-600 dark:text-amber-400', bgColor: 'bg-amber-50 dark:bg-amber-900/30' },
  { status: 'done', label: '已完成', color: 'text-emerald-600 dark:text-emerald-400', bgColor: 'bg-emerald-50 dark:bg-emerald-900/30' },
]

// 按状态筛选任务
function getTasksByStatus(status: TaskStatus): Task[] {
  return props.tasks.filter(t => t.status === status)
}

// 拖拽状态
const draggedTaskId = ref<string | null>(null)
const dragOverColumn = ref<TaskStatus | null>(null)

// 删除确认状态
const confirmingDeleteId = ref<string | null>(null)

function requestDelete(id: string) {
  if (confirmingDeleteId.value === id) {
    emit('delete', id)
    confirmingDeleteId.value = null
  } else {
    confirmingDeleteId.value = id
    setTimeout(() => { confirmingDeleteId.value = null }, 3000)
  }
}

function onDragStart(task: Task) {
  draggedTaskId.value = task.id
}

function onDragOver(status: TaskStatus) {
  dragOverColumn.value = status
}

function onDragLeave() {
  dragOverColumn.value = null
}

function onDrop(status: TaskStatus) {
  if (draggedTaskId.value) {
    emit('update-status', draggedTaskId.value, status)
  }
  draggedTaskId.value = null
  dragOverColumn.value = null
}

function onDragEnd() {
  draggedTaskId.value = null
  dragOverColumn.value = null
}
</script>

<template>
  <div class="grid grid-cols-3 gap-4">
    <!-- 每一列 -->
    <div
      v-for="col in columns"
      :key="col.status"
      class="rounded-xl border-2 transition-colors duration-150"
      :class="dragOverColumn === col.status ? 'border-indigo-300 dark:border-indigo-500 bg-indigo-50/50 dark:bg-indigo-900/20' : 'border-transparent'"
    >
      <!-- 列头 -->
      <div class="flex items-center justify-between px-4 py-3">
        <div class="flex items-center gap-2">
          <h3 class="text-sm font-semibold" :class="col.color">
            {{ col.label }}
          </h3>
          <span
            class="inline-flex items-center justify-center w-5 h-5 rounded-full text-xs font-medium"
            :class="col.bgColor + ' ' + col.color"
          >
            {{ getTasksByStatus(col.status).length }}
          </span>
        </div>
      </div>

      <!-- 拖放区域 -->
      <div
        class="px-3 pb-3 min-h-[200px] flex flex-col gap-3"
        @dragover.prevent="onDragOver(col.status)"
        @dragleave="onDragLeave"
        @drop="onDrop(col.status)"
      >
        <div
          v-for="task in getTasksByStatus(col.status)"
          :key="task.id"
          draggable="true"
          class="bg-white dark:bg-slate-800 rounded-lg shadow-sm border border-slate-200 dark:border-slate-700 border-l-4 p-3 cursor-grab active:cursor-grabbing transition-transform duration-150 hover:scale-[1.02]"
          :class="[
            priorityBorder[task.priority],
            draggedTaskId === task.id ? 'opacity-40 scale-95' : '',
          ]"
          @dragstart="onDragStart(task)"
          @dragend="onDragEnd"
        >
          <!-- 卡片顶部：标题 + 删除 -->
          <div class="flex items-start justify-between gap-2">
            <h4
              class="text-sm font-medium leading-snug"
              :class="task.status === 'done' ? 'line-through text-slate-400 dark:text-slate-500' : 'text-slate-800 dark:text-slate-100'"
            >
              {{ task.title }}
            </h4>
            <button
              class="shrink-0 w-5 h-5 flex items-center justify-center rounded-full transition-colors"
              :class="confirmingDeleteId === task.id
                ? 'bg-rose-500 text-white hover:bg-rose-600 dark:bg-rose-600 dark:hover:bg-rose-700'
                : 'text-slate-300 dark:text-slate-600 hover:text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-900/30'"
              :title="confirmingDeleteId === task.id ? '再次点击确认删除' : '删除任务'"
              @click.stop="requestDelete(task.id)"
            >
              <svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            </button>
          </div>

          <!-- 描述 -->
          <p v-if="task.description" class="text-xs text-slate-400 dark:text-slate-500 mt-1 line-clamp-2">
            {{ task.description }}
          </p>

          <!-- 底部：优先级 + 复选框 -->
          <div class="flex items-center justify-between mt-2.5">
            <span
              class="inline-flex items-center px-1.5 py-0.5 rounded text-[11px] font-medium"
              :class="priorityBadge[task.priority]"
            >
              {{ priorityLabel[task.priority] }}
            </span>
            <label class="flex items-center cursor-pointer">
              <input
                type="checkbox"
                :checked="task.status === 'done'"
                class="w-3.5 h-3.5 rounded border-slate-300 text-indigo-600 cursor-pointer accent-indigo-600"
                @change="emit('toggle', task.id)"
              />
            </label>
          </div>
        </div>

        <!-- 列内空状态 -->
        <div
          v-if="getTasksByStatus(col.status).length === 0"
          class="flex-1 flex items-center justify-center text-xs text-slate-300 dark:text-slate-600 py-8"
        >
          拖拽任务到此处
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/KanbanBoard.tsx
import { useState } from 'react'
import type { Task, TaskStatus } from '../types/task'
import { priorityBorder, priorityLabel, priorityBadge } from '../constants/task'
import { useTaskStore } from '../store/taskStore'
import DeleteConfirmModal from './DeleteConfirmModal'

const columns: { status: TaskStatus; label: string; color: string; bgColor: string }[] = [
  { status: 'todo', label: '待办', color: 'text-slate-600 dark:text-slate-400', bgColor: 'bg-slate-50 dark:bg-slate-700' },
  { status: 'in-progress', label: '进行中', color: 'text-amber-600 dark:text-amber-400', bgColor: 'bg-amber-50 dark:bg-amber-900/30' },
  { status: 'done', label: '已完成', color: 'text-emerald-600 dark:text-emerald-400', bgColor: 'bg-emerald-50 dark:bg-emerald-900/30' },
]

export default function KanbanBoard() {
  const tasks = useTaskStore((s) => s.tasks)
  const updateTask = useTaskStore((s) => s.updateTask)
  const toggleTask = useTaskStore((s) => s.toggleTask)
  const deleteTask = useTaskStore((s) => s.deleteTask)

  const [draggedTaskId, setDraggedTaskId] = useState<string | null>(null)
  const [dragOverColumn, setDragOverColumn] = useState<TaskStatus | null>(null)
  const [deleteTarget, setDeleteTarget] = useState<Task | null>(null)

  function getTasksByStatus(status: TaskStatus): Task[] {
    return tasks.filter((t) => t.status === status)
  }

  function onDragStart(task: Task) {
    setDraggedTaskId(task.id)
  }

  function onDragOver(status: TaskStatus) {
    setDragOverColumn(status)
  }

  function onDragLeave() {
    setDragOverColumn(null)
  }

  function onDrop(status: TaskStatus) {
    if (draggedTaskId) {
      updateTask(draggedTaskId, { status })
    }
    setDraggedTaskId(null)
    setDragOverColumn(null)
  }

  function onDragEnd() {
    setDraggedTaskId(null)
    setDragOverColumn(null)
  }

  return (
    <>
      <div className="grid grid-cols-3 gap-4">
        {columns.map((col) => (
          <div
            key={col.status}
            className={`rounded-xl border-2 transition-colors duration-150 ${dragOverColumn === col.status ? 'border-indigo-300 dark:border-indigo-500 bg-indigo-50/50 dark:bg-indigo-900/20' : 'border-transparent'}`}
          >
            {/* 列头 */}
            <div className="flex items-center justify-between px-4 py-3">
              <div className="flex items-center gap-2">
                <h3 className={`text-sm font-semibold ${col.color}`}>{col.label}</h3>
                <span className={`inline-flex items-center justify-center w-5 h-5 rounded-full text-xs font-medium ${col.bgColor} ${col.color}`}>
                  {getTasksByStatus(col.status).length}
                </span>
              </div>
            </div>

            {/* 拖放区域 */}
            <div
              className="px-3 pb-3 min-h-[200px] flex flex-col gap-3"
              onDragOver={(e) => { e.preventDefault(); onDragOver(col.status) }}
              onDragLeave={onDragLeave}
              onDrop={() => onDrop(col.status)}
            >
              {getTasksByStatus(col.status).map((task) => (
                <div
                  key={task.id}
                  draggable
                  className={`bg-white dark:bg-slate-800 rounded-lg shadow-sm border border-slate-200 dark:border-slate-700 border-l-4 p-3 cursor-grab active:cursor-grabbing transition-transform duration-150 hover:scale-[1.02] ${priorityBorder[task.priority]} ${draggedTaskId === task.id ? 'opacity-40 scale-95' : ''}`}
                  onDragStart={() => onDragStart(task)}
                  onDragEnd={onDragEnd}
                >
                  {/* 卡片头部 */}
                  <div className="flex items-start justify-between gap-2">
                    <h4 className={`text-sm font-medium leading-snug ${task.status === 'done' ? 'line-through text-slate-400 dark:text-slate-500' : 'text-slate-800 dark:text-slate-100'}`}>
                      {task.title}
                    </h4>
                    <button
                      onClick={() => setDeleteTarget(task)}
                      className="shrink-0 w-5 h-5 flex items-center justify-center rounded-full text-slate-300 dark:text-slate-600 hover:text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-900/30 transition-colors"
                      title="删除"
                    >
                      <svg xmlns="http://www.w3.org/2000/svg" className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                        <line x1="18" y1="6" x2="6" y2="18" />
                        <line x1="6" y1="6" x2="18" y2="18" />
                      </svg>
                    </button>
                  </div>

                  {/* 描述 */}
                  {task.description && (
                    <p className="text-xs text-slate-400 dark:text-slate-500 mt-1 line-clamp-2">{task.description}</p>
                  )}

                  {/* 底部信息 */}
                  <div className="flex items-center justify-between mt-2.5 flex-wrap gap-1">
                    <div className="flex items-center gap-1.5">
                      <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-[11px] font-medium ${priorityBadge[task.priority]}`}>
                        {priorityLabel[task.priority]}
                      </span>
                      {task.category && (
                        <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[11px] font-medium bg-indigo-50 text-indigo-600 dark:bg-indigo-900/30 dark:text-indigo-400">
                          {task.category}
                        </span>
                      )}
                    </div>
                    <label className="flex items-center cursor-pointer">
                      <input
                        type="checkbox"
                        checked={task.status === 'done'}
                        onChange={() => toggleTask(task.id)}
                        className="w-3.5 h-3.5 rounded border-slate-300 text-indigo-600 cursor-pointer accent-indigo-600"
                      />
                    </label>
                  </div>
                </div>
              ))}

              {/* 空列提示 */}
              {getTasksByStatus(col.status).length === 0 && (
                <div className="flex-1 flex items-center justify-center text-xs text-slate-300 dark:text-slate-600 py-8">
                  拖拽任务到此处
                </div>
              )}
            </div>
          </div>
        ))}
      </div>

      <DeleteConfirmModal
        isOpen={!!deleteTarget}
        taskTitle={deleteTarget?.title ?? ''}
        onConfirm={() => { if (deleteTarget) { deleteTask(deleteTarget.id); setDeleteTarget(null) } }}
        onCancel={() => setDeleteTarget(null)}
      />
    </>
  )
}
